### PR TITLE
NETOBSERV-69 using goflow2 as a library: make the flow process routine cancellable

### PR DESCRIPTION
**Pull request by jpinsonneau**
This PR implements goflow shutdown function on ctx.Done call

It uses context.TODO() until we implements cancellation scenario 

I have used time.Sleep in the TestShutdown function to wait for calls but feel free to suggest if there is a better way to do it like race ?

### CODE REVIEW

**Comment by mariomac** [comment]
LGTM, however I'm afraid that the tests might become flaky if we just wait one minute. Maybe we can incorporate this `Eventually` tool: https://github.com/newrelic/infrastructure-agent/blob/30d0e84f3526ab0e1398d7908cc6e73193a21109/internal/testhelpers/test_helpers.go#L205

Then you can check the values like:

```go
Eventually(t, time.Second, func(t) {
    assert.Equal(t, true, spy.nextCalled)
})
```

**Comment by mariomac** [comment]
Actually, `assert` and `require` packages now have their own `Eventually` function.

**Comment by mariomac** [comment]
LGTM, but linting is failing

**Comment by jpinsonneau** [comment]
> LGTM, but linting is failing

Thx ! I forgot to run that

**Pull request merged**
